### PR TITLE
fix: Handle 429 responses from Chat API

### LINKED ISSUE #40: Handle 429 responses from Google Chat API
Since 01 November 2024, daily runs of prnouncer (in [`guardian/prnouncer-config`](https://github.com/guardian/prnouncer-config)) have failed to send a complete list of open pull requests.

The [logs](https://github.com/guardian/prnouncer-config/actions/runs/11659961340/job/32461385411) show a 429 response from the Google Chat API [not being handled](https://github.com/guardian/actions-prnouncer/blob/3422cbc0ce79ff3bb4965ea56929a07e827414a3/src/google.rs#L35-L53).

Image

Though its not [an official change](https://developers.google.com/workspace/chat/docs/release-notes), it looks like this API has (new?) usage limits described here - https://developers.google.com/workspace/chat/limits.

This GitHub Action only calls uses the `spaces.messages.create` API, which has a limit of 60 requests per minute. Can we gracefully handle the 429 response such that all open pull requests are posted?

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?
Retry a Google Chat API request 1.5 seconds after receipt of a 429 response. This should help avoid the [rate limit](https://developers.google.com/workspace/chat/limits) of this API (60 requests per minute).

<details><summary>Example output w/unhandled 429 responses</summary>
<p>

image

</p>
</details>

## How to test
Following the README instructions:
- Run `main`, observe a 429 response and program exit
- Run this branch and observe a retry on a 429 response

Alternatively, see https://github.com/guardian/prnouncer-config/pull/71 and it's [execution](https://github.com/guardian/prnouncer-config/actions/runs/11679203311/job/32519906013).

---
Fixes #40.

### CODE REVIEW

File: src/google.rs [hunk 1]
```diff
@@ -40,15 +42,33 @@ impl GoogleChatMessage {
...
+            /*
+            Sleep for 1.5 seconds to avoid rate limiting, at 60 requests per minute.
+            See https://developers.google.com/workspace/chat/limits
+            */
+            info!(
+                "Received {} response. Sleeping for 1.5 seconds before retrying",
+                response.status()
+            );
+            tokio::time::sleep(time::Duration::from_millis(1500)).await;
+            Box::pin(self.send(webhook_url, thread_key)).await
```
Comment (akash1810) [inline src/google.rs:60]: A terminating `;` doesn't compile. I don't know Rust well enough to comment why - any help welcome!

Comment (shtukas) [reply src/google.rs:60]: Expressions without a semicolon return a value to the containing function or block. Expressions with a semicolon become statements and do not return a value.

**Review by shtukas — APPROVED** [review]
